# Generated by Django 3.1.2 on 2020-10-02 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_departure_time', models.CharField(max_length=10)),
                ('assigned_plane_type', models.CharField(max_length=400)),
                ('capacity', models.IntegerField()),
                ('seats_reserved', models.IntegerField()),
                ('seats_available', models.IntegerField()),
            ],
        ),
    ]
